// Code generated by go tool dist; DO NOT EDIT.

package buildcfg

import "runtime"

const defaultGO386 = `sse2`
const defaultGOARM = `5`
const defaultGOMIPS = `hardfloat`
const defaultGOMIPS64 = `hardfloat`
const defaultGOPPC64 = `power8`
const defaultGOEXPERIMENT = ``
const defaultGO_EXTLINK_ENABLED = ``
const defaultGO_LDSO = ``
const version = `devel go1.17-cb34026a95 Tue Apr 27 05:44:56 2021 +0000`
const defaultGOOS = runtime.GOOS
const defaultGOARCH = runtime.GOARCH
